---
- name: ANSISTRANO | GIT | Ensure GIT deployment key is up to date
  template:
    src: "{{ ansistrano_git_identity_key_path }}"
    dest: "{{ ansistrano_deploy_to }}/git_identity_key"
    mode: 0400
  when: ansistrano_git_identity_key_path|trim != ""

- name: ANSISTRANO | GIT | Update remote repository
  git:
    repo: "{{ ansistrano_git_repo }}"
    dest: "{{ ansistrano_deploy_to }}/repo"
    version: "{{ ansistrano_git_branch }}"
    accept_hostkey: true
    update: yes
    force: yes
  register: ansistrano_git_result
  when: ansistrano_git_identity_key_path|trim == ''

- name: ANSISTRANO | GIT | Update remote repository using SSH key
  git:
    repo: "{{ ansistrano_git_repo }}"
    dest: "{{ ansistrano_deploy_to }}/repo"
    version: "{{ ansistrano_git_branch }}"
    accept_hostkey: true
    update: yes
    force: yes
    key_file: "{{ ansistrano_deploy_to }}/git_identity_key"
  register: ansistrano_git_result
  when: ansistrano_git_identity_key_path|trim != ""

- name: ANSISTRANO | GIT | Shred GIT deployment key
  command: shred -f "{{ ansistrano_deploy_to }}/git_identity_key"
  when: ansistrano_git_identity_key_path|trim != ""

- name: ANSISTRANO | GIT | Export a copy of the repo
  command: git checkout-index -f -a --prefix="{{ ansistrano_release_path.stdout }}/"
  args:
    chdir: "{{ ansistrano_deploy_to }}/repo"
