---
- hosts: web-magento-servers

  vars_files:
    - vars/carlosbuenosvinos.ansistrano-deploy/main.yml

  roles:
    - role: carlosbuenosvinos.ansistrano-deploy
      become: no

  pre_tasks:
  - name: Ensures composer home directory exists
    become: no
    file: path=.composer state=directory

  - name: auth.json
    become: no
    template: src=templates/.composer/auth.json.j2 dest=.composer/auth.json

  - name: Ensures main directory exists
    become: yes
    become_method: sudo
    file: path={{ ansistrano_deploy_to }} state=directory
      mode=u=rwX,g=rwX,o=rX
      owner={{ magento_owner }} group={{ magento_group }}
      recurse=yes
